services:
  ubuntu:
    image: ubuntu:22.04
  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
  backend:
    build:
      context: ./backend
    volumes:
      - ./storage/images:/images
    depends_on:
      - redis
  redis:
    image: redis
    command:
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - ./storage/db:/data
