services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./storage/images:/images
    depends_on:
      - redis
    ports:
      - 8000:5000
  redis:
    image: redis
    command:
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - ./storage/db:/data
