services:
  react-app:
    build:
      context: ./frontend
    ports:
      - 80:80
  rust-actix:
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./storage/images:/images
    depends_on:
      - redis
  redis:
    image: redis
    command:
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - ./storage/db:/data
