[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-multipart = "0.6.1"
futures-util = "0.3"
env_logger = "0.10.0"
mime = "0.3.17"
tokio = { version = "1", features = ["fs"] }
redis = "*"
